 version: 2.1

 orbs:
   win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
     steps:
      - checkout
      #- run: msbuild /t:Restore
      #- run: msbuild /t:Build	
      - run: echo "ready"
      
